### PR TITLE
add motors support to jooan a6m, pcb silk: A1A_A_VB

### PR DESCRIPTION
**Pull request by jimsmt**

### CODE REVIEW

**Comment by nicolasroche898** [comment]
Motors on the Jooan A6M ??

IMG_20240812_215018

IMG_20240812_215608

**Comment by nicolasroche898** [comment]
interesting. maybe mine is "A6M-U" without motors and yours is "A6M" with motors ? can you send picture of camera and link to buy? also picture of camera label if any

**Comment by themactep** [comment]
@jimsmt we will need a separate profile for that camera. let's not mix different hardware just because they use same modules.

**Comment by nicolasroche898** [comment]
> we will need a separate profile for that camera. let's not mix different hardware just because they use same modules.

@themactep can you move jooan_q3r out of testing? I think this closely related to his camera - same board as a6m, but with 2 motors.

**Comment by themactep** [comment]
moved that one and two more. seems they all use the same board.

**Pull request closed without merging**
