### PR TITLE
Fix command lines for new motors binary

### PR DESCRIPTION
**Pull request by roleoroleo**
The new binary doesn't handle -q param to remove printf to stdout.
So, redirect to /dev/null

### CODE REVIEW

**Comment by roleoroleo** [comment]
Please, wait to merge this pr: there is a problem with sed.

**Comment by gtxaspec** [comment]
@roleoroleo do we need dev null redirect? the new motors binary should be silent on commands

**Comment by roleoroleo** [comment]
You're right, I didn't notice.
I remove just -q.

**Comment by roleoroleo** [comment]
I removed /dev/null redirect.
Finally, this pr simply removes -q options, not supported with the new motors binary.

**Comment by yangminglong** [comment]
This commit make #99  (NVIF PTZ improvements) deleted,  @pauln Is there a problem here.

**Comment by gtxaspec** [comment]
the motors program was refactored, with updates merged.  check the motors repo for the latest code.

**Pull request merged**
