### PR TITLE
Fix some bugs in sysupgrade

### PR DESCRIPTION
**Pull request by felipecrs**
ShellCheck helped me find some bugs. I have fixed everything.

Some highlights:

1. Script was not failing if user passed more than one arg (even though it only supports one)
2. Script was not failing when using passes a wrong option (was exiting with 0)
3. Not erroring when user pass -f or -p, but also passes an arg
3. An upgrade file with a space like `sysupgrade 'thingino (2).bin'` would probably make it explode

But this list is not complete.

I also formatted the code with shfmt. I hope you don't mind (let me know otherwise).

### CODE REVIEW

**Comment by felipecrs** [comment]
Please don't review yet, I still need to test it.

**Comment by felipecrs** [comment]
Tested a bunch of scenarios, caught some other issues, should be good to go now.

**Comment by felipecrs** [comment]
This PR is best reviewed with ignoring white spaces differences:

https://github.com/themactep/thingino-firmware/pull/364/files?w=1

**Comment by felipecrs** [comment]
@themactep, given your pace, this PR will become outdated very frequently unless it gets merged.

Could you please take a look on it? If you dislike some of the changes, let's talk through them.

No need to write comprehensive review comments, just pinpoint things you don't like or want changed.

**Comment by themactep** [comment]
Ah, I did not see you marked it ready to merge. Last time I checked it still was wip.

Okay, at a quick glance. We do not need to quote things just in case or to make shellcheck happy. Say, if I write `cp $abc/def $xyz/$1` and I know that no `$abc` nor `$1` are going to have anything but valid characters, the quotes are redundant.

No need for shellcheck comments in the code. It is an embedded device, every non-functional character is a waste of valuable space.

Then, I don't agree with changing formatting in help message nor expanding some routines in argument handling. I am not here to make shellcheck happy. I maintain that script and it it easier for me to have it the way it is.

Overall, the PR has too many controversial changes to have a chance to be accepted as is. You are fixing thing that are not broken, not adding any new functionality. That brings the question: why?

**Comment by felipecrs** [comment]
@themactep, I absolutely understand there is no need to make shellcheck happy and neither any formatter. Thus, I will revert these sections accordingly.

However, maybe you missed this part of the PR description:

> 1. An upgrade file with a space like sysupgrade 'thingino (2).bin' would probably make it explode

I say probably because I didn't dare trying it, but I am very confident it would not work without this PR.

**Comment by themactep** [comment]
See, you are creating solutions that yet need to find an issue. No file on github, nor a file generated by buildroot will have a name with a space ot it. And these are the primary sources for such upgrades. Do not try to solve hypothetical issues unless you have a real case on hands.

**Comment by gtxaspec** [comment]
@themactep i disagree regarding:

`An upgrade file with a space like sysupgrade 'thingino (2).bin' would probably make it explode`
i just encountered this now and was about to make an issue.  the script needs to take filenames, even with spaces. 

perhaps a simpler implementation, I haven't looked at the code here yet.  todo.

**Comment by themactep** [comment]
How did you end up with a name like that and how did you run the script to make it fail?

**Comment by felipecrs** [comment]
> How did you end up with a name like that

If you download the same file twice with Chrome, even from different releases, it will end up like that.

> and how did you run the script to make it fail?

The way it's supposed to be ran (?):

```
sysupgrade 'thingino (2).bin'
```

**Pull request closed without merging**
